services:
  nginx:
    image: nginx:1.25-alpine
    container_name: maruska_nginx
    depends_on:
      - app
    volumes:
      - ./public:/var/www/public:ro          # hotový frontend z hostu
      - ./docker/prod/nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
      - storage_data:/var/www/storage
      - database_data:/var/www/database
    labels:
      - "traefik.enable=true"

      # HTTPS router
      - "traefik.http.routers.maruska.rule=Host(`umaruskyzlin.cz`) || Host(`www.umaruskyzlin.cz`)"
      - "traefik.http.routers.maruska.entrypoints=websecure"
      - "traefik.http.routers.maruska.tls.certresolver=cloudflare"
      - "traefik.http.services.maruska.loadbalancer.server.port=80"

      # HTTP -> HTTPS redirect
      - "traefik.http.routers.maruska-http.rule=Host(`umaruskyzlin.cz`) || Host(`www.umaruskyzlin.cz`)"
      - "traefik.http.routers.maruska-http.entrypoints=web"
      - "traefik.http.routers.maruska-http.middlewares=maruska-redirect-to-https"

      - "traefik.http.middlewares.maruska-redirect-to-https.redirectscheme.scheme=https"
    networks:
      - traefik
      - maruska
    restart: unless-stopped

  app:
    container_name: maruska_app
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    image: maruska-prod:latest
    working_dir: /var/www
    env_file:
      - ./.env.production
    volumes:
      - ./public:/var/www/public:cached        # mount frontend z hostu
      - database_data:/var/www/database
      - storage_data:/var/www/storage
      - ./.env.production:/var/www/.env:ro
    expose:
      - "9000"
    networks:
      - maruska
    restart: unless-stopped
    command: >
      sh -c "php artisan optimize:clear &&
             php-fpm -F"                       

volumes:
  storage_data:
  database_data:

networks:
  traefik:
    external: true
  maruska:
    external: true
