services:
  nginx:
    image: nginx:1.25-alpine
    container_name: ama_nginx
    depends_on:
      - app
    volumes:
      - ./public:/var/www/public:ro          # hotový frontend z hostu
      - ./docker/prod/nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
      - storage_data:/var/www/storage
      - database_data:/var/www/database
    labels:
      - "traefik.enable=true"

      # HTTPS router
      - "traefik.http.routers.ama.rule=Host(`amatelier.cz`) || Host(`www.amatelier.cz`)"
      - "traefik.http.routers.ama.entrypoints=websecure"
      - "traefik.http.routers.ama.tls.certresolver=cloudflare"
      - "traefik.http.services.ama.loadbalancer.server.port=80"

      # HTTP -> HTTPS redirect
      - "traefik.http.routers.ama-http.rule=Host(`amatelier.cz`) || Host(`www.amatelier.cz`)"
      - "traefik.http.routers.ama-http.entrypoints=web"
      - "traefik.http.routers.ama-http.middlewares=ama-redirect-to-https"

      - "traefik.http.middlewares.ama-redirect-to-https.redirectscheme.scheme=https"
    networks:
      - traefik
      - ama
    restart: unless-stopped

  app:
    container_name: ama_app
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    image: ama-prod:latest
    working_dir: /var/www
    env_file:
      - ./.env.production
    volumes:
      - ./public:/var/www/public:cached        # mount frontend z hostu
      - database_data:/var/www/database
      - storage_data:/var/www/storage
      - ./.env.production:/var/www/.env:ro
    expose:
      - "9000"
    networks:
      - ama
    restart: unless-stopped
    command: >
      sh -c "php artisan optimize:clear &&
             php-fpm -F"                       # FPM běží na popředí

volumes:
  storage_data:
  database_data:

networks:
  traefik:
    external: true
  ama:
    external: true
